#!/usr/bin/env bash

set -e

cd $HOME

if [ ! -d "$HOME/Autoware" ]; 
    then
	    echo "Autoware not found in home folder. Exiting Now!"
        exit 1
fi

cd $HOME/
mkdir .autoware -p && cd .autoware
wget http://db3.ertl.jp/autoware/sample_data/my_launch.sh
wget http://db3.ertl.jp/autoware/sample_data/sample_moriyama_data.tar.gz
wget http://db3.ertl.jp/autoware/sample_data/sample_moriyama_150324.tar.gz

tar xfz sample_moriyama_data.tar.gz
tar xfz sample_moriyama_150324.tar.gz

sh my_launch.sh